spring.application.name=api-service
server.port=8080

# OpenWeather API YOUR_OPENWEATHER_API_KEY
openweather.api.key=YOUR_OPENWEATHER_API_KEY
openweather.api.url=https://api.openweathermap.org/data/2.5/weather
openweather.api.units=metric
openweather.api.lang=ua

# ExchangeRates API
exchangerates.api.key=cb917293f4ea2b0aa0e6f8b3
exchangerates.api.url=https://v6.exchangerate-api.com/v6

# Cache config (seconds)
cache.weather.ttl=600
cache.currency.ttl=3600

# Logging
logging.level.com.lab=DEBUG
logging.level.org.springframework.web=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/app.log