spring.application.name=telegram-bot
server.port=8081

telegram.bot.token=YOUR_OPENWEATHER_API_KEY
telegram.bot.username=verificate_userinfo_bot

api.service.url=http://localhost:8080

# ??? 4: SQLite ???? ?????
# ???? user_data.db ??????????? ??????????? ? ????? ???????
spring.datasource.url=jdbc:sqlite:./user_data.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Logging
logging.level.edu.ilkiv=DEBUG
logging.level.org.springframework.web=INFO
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{20} - %msg%n
logging.file.name=logs/bot-service.log
