spring.application.name=telegram-bot
server.port=8081

telegram.bot.token=8043650755:AAF3Sx4wzcCnwkHGSbvseva0mtTUMH5CKh8
telegram.bot.username=verificate_userinfo_bot

api.service.url=http://localhost:8080

logging.level.edu.ilkiv=DEBUG
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{20} - %msg%n
logging.file.name=logs/bot-service.log